services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:2345@db:5432/cryptoballot
    depends_on:
      - db
    

  signup:
    build: ./signup
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=postgres://postgres:2345@db:5432/cryptoballot
    depends_on:
      - db
  
  login:
    build: ./login
    ports:
      - "4002:4002"
    environment:
      - DATABASE_URL=postgres://postgres:2345@db:5432/cryptoballot
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2345          
      POSTGRES_DB: cryptoballot        
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

networks:
  default:
    name: app_network
